---
title: "PARA Veg Map Comparison"
author: "Sarah Wright"
date: "February 28, 2018"
output: html_document
runtime: shiny
---

```{r setup, include=FALSE, warning = FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(shiny)
library(tidyverse)
library(plotly)
```

```{r import, echo = FALSE}
veg.compare <- read.csv("M:/GIS/Projects/PARA_IU/PARA_NPSVeg_Landfire_20180228.csv", as.is = TRUE) %>%
    select(Landfire, NPS_S, NPS_C, Area_m2) %>%
    mutate(Area_m2 = round(Area_m2, digits = 0))
```

## How does LANDFIRE classify each veg map category?
```{r byvegmap, echo = FALSE}
selectInput("VegMapClass", label = "Select an NPS veg map category", choices = unique(veg.compare$NPS_S))
```

```{r plotlandfirebyvegmap, echo = FALSE}
landfire.classes <- reactive({
    filter(veg.compare, NPS_S == input$VegMapClass)
})

renderPlotly({
    plot_ly(landfire.classes(), labels = ~Landfire, values = ~Area_m2, type = "pie") %>%
        layout(xaxis = list(showticklabels = FALSE))
})
```

## Which veg map categories are associated with each LANDFIRE category?
```{r bylandfire, echo = FALSE}
selectInput("LandfireClass", label = "Select a LANDFIRE category", choices = unique(veg.compare$Landfire))
```

```{r plotvegmapbylandfire, echo = FALSE}
vegmap.classes <- reactive({
    filter(veg.compare, Landfire == input$LandfireClass)
})

renderPlotly({
    plot_ly(vegmap.classes(), x = ~NPS_S, y = ~Area_m2, type = "bar") %>%
        layout(xaxis = list(showticklabels = FALSE))
})
```

## How accurately can we predict Artemisia based only on LANDFIRE categories?
```{r echo = FALSE, warning = FALSE, message = FALSE}
# Filter out everything that is not classified as Artemisia in the NPS veg map, then get list of LANDFIRE categories that fall within those areas
artemisia.only <- filter(veg.compare, grepl("*Artemisia*", NPS_S, ignore.case = TRUE)) %>%
    group_by(Landfire, NPS_S, NPS_C) %>%
    summarise(Area_m2 = sum(Area_m2))
possible.lf.artemisia <- select(artemisia.only, Landfire) %>%
    unique()

# For each LF (LANDFIRE) category that could be Artemisia, find out what percentage of area covered by that LF category is classified as Artemisia by the NPS veg map
lf.total.areas <- filter(veg.compare, Landfire %in% possible.lf.artemisia$Landfire) %>%
    group_by(Landfire) %>%
    summarise(TotalArea_m2 = sum(Area_m2))
artemisia.pct <- inner_join(artemisia.only, lf.total.areas, by = "Landfire") %>%
    mutate(PercentTotalLFArea = 100 * (Area_m2 / TotalArea_m2), PercentTotalLFArea = round(PercentTotalLFArea, digits = 2)) %>%
    select(-NPS_C, -Area_m2) %>%
    spread(NPS_S, PercentTotalLFArea) %>%
    rename(ARTR2_Shrubland_pct = `Artemisia tridentata Shrubland Alliance`,
           ARTEM_PIED_JUOS_pct = `Pinus edulis - Juniperus osteosperma / Artemisia Woodland Alliance`) %>%
    mutate(ARTR2_Shrubland_pct = if_else(is.na(ARTR2_Shrubland_pct), 0, ARTR2_Shrubland_pct),
           ARTEM_PIED_JUOS_pct = if_else(is.na(ARTEM_PIED_JUOS_pct), 0, ARTEM_PIED_JUOS_pct),
           All_ARTEM_pct = ARTR2_Shrubland_pct + ARTEM_PIED_JUOS_pct)
```

```{r echo = FALSE}
renderDataTable({
    artemisia.pct
})
```